package snack.buyer.panels;

import snack.db.DatabaseConnection;
import snack.util.UIConstants;

import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import java.awt.*;
import java.sql.*;

public class MyBillsPanel extends JPanel {

    private final int custId;
    private JTable table;
    private DefaultTableModel model;

    private static final String[] COLS = {
        "Bill ID","Order ID","Bill Date","Snack","Qty","Subtotal (₹)","Tax 18% (₹)","Total (₹)","Status"
    };

    public MyBillsPanel(int custId) {
        this.custId = custId;
        setLayout(new BorderLayout());
        setBackground(UIConstants.BG);
        buildUI();
        loadData();
    }

    private void buildUI() {
        add(UIConstants.makeTitlePanel("My Bills",
            "Bills auto-generated by your dealer — includes 18% GST"), BorderLayout.NORTH);

        model = new DefaultTableModel(COLS, 0);
        table = UIConstants.makeTable(model);
        JScrollPane sp = new JScrollPane(table);
        sp.getViewport().setBackground(UIConstants.WHITE);

        JButton btnRefresh = UIConstants.btnRefresh();
        JButton btnPrint   = UIConstants.makeButton("🖨 Print Bill", UIConstants.ACCENT);
        JButton btnSummary = UIConstants.makeButton("💰 Summary", UIConstants.SUCCESS);
        add(UIConstants.makeButtonBar(btnRefresh, btnPrint, btnSummary), BorderLayout.SOUTH);
        add(sp, BorderLayout.CENTER);

        btnRefresh.addActionListener(e -> loadData());
        btnPrint.addActionListener(e   -> printBill());
        btnSummary.addActionListener(e -> showSummary());
    }

    private void loadData() {
        model.setRowCount(0);
        try {
            PreparedStatement ps = DatabaseConnection.getConnection().prepareStatement(
                "SELECT b.Bill_ID, b.Order_ID, b.Bill_date, " +
                "  sn.Snack_Name, o.Order_Quantity, " +
                "  o.Total_price, b.Tax, b.Total_Amount, o.status " +
                "FROM Bill b " +
                "JOIN Orders o  ON b.Order_ID  = o.Order_ID " +
                "JOIN Snacks sn ON o.Snack_ID   = sn.Snack_ID " +
                "WHERE b.cust_ID=? ORDER BY b.Bill_date DESC");
            ps.setInt(1, custId);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt(1), rs.getInt(2), rs.getString(3),
                    rs.getString(4), rs.getInt(5),
                    String.format("₹ %.2f", rs.getDouble(6)),
                    String.format("₹ %.2f", rs.getDouble(7)),
                    String.format("₹ %.2f", rs.getDouble(8)),
                    rs.getString(9)
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"DB Error: "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void printBill() {
        int r = table.getSelectedRow();
        if (r < 0) { JOptionPane.showMessageDialog(this,"Select a bill.","Info",JOptionPane.WARNING_MESSAGE); return; }
        String billId = model.getValueAt(r,0).toString();
        String ordId  = model.getValueAt(r,1).toString();
        String receipt = String.format("""
            ╔════════════════════════════════╗
            ║       SNACK DEALER RECEIPT      ║
            ╠════════════════════════════════╣
            ║  Bill ID    : %-16s  ║
            ║  Order ID   : %-16s  ║
            ║  Date       : %-16s  ║
            ╠════════════════════════════════╣
            ║  Item       : %-16s  ║
            ║  Qty        : %-16s  ║
            ╠════════════════════════════════╣
            ║  Subtotal   : %-16s  ║
            ║  Tax (18%%) : %-16s  ║
            ║  TOTAL      : %-16s  ║
            ╠════════════════════════════════╣
            ║  Status     : %-16s  ║
            ╚════════════════════════════════╝
            """,
            billId, ordId,
            model.getValueAt(r,2),
            model.getValueAt(r,3),
            model.getValueAt(r,4),
            model.getValueAt(r,5),
            model.getValueAt(r,6),
            model.getValueAt(r,7),
            model.getValueAt(r,8)
        );
        JTextArea ta = new JTextArea(receipt);
        ta.setFont(new Font("Monospaced",Font.PLAIN,13));
        ta.setEditable(false);
        ta.setBackground(new Color(250,250,250));
        JOptionPane.showMessageDialog(this, new JScrollPane(ta),
            "Bill #"+billId, JOptionPane.PLAIN_MESSAGE);
    }

    private void showSummary() {
        try {
            PreparedStatement ps = DatabaseConnection.getConnection().prepareStatement(
                "SELECT COUNT(*), COALESCE(SUM(Total_Amount),0), COALESCE(SUM(Tax),0) " +
                "FROM Bill WHERE cust_ID=?");
            ps.setInt(1, custId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this,
                    String.format("<html>" +
                        "<h2 style='color:#1A237E'>Spending Summary</h2>" +
                        "<table>" +
                        "<tr><td>Total Bills   :</td><td><b>%d</b></td></tr>" +
                        "<tr><td>Total Tax Paid:</td><td><b>₹ %.2f</b></td></tr>" +
                        "<tr><td>Grand Total   :</td><td><b style='color:green'>₹ %.2f</b></td></tr>" +
                        "</table></html>",
                        rs.getInt(1), rs.getDouble(3), rs.getDouble(2)),
                    "My Spending", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"DB Error: "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
}